services:
  api:
    container_name: f8-k13-day58a
    image: node:22.9.0
    working_dir: /app/api
    volumes:
      - ./api:/app/api
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
    command: ["npm", "run", "start:dev"]


  db:
    container_name: f8-k13-db_250729
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    ports:
      - "5001:5432"
    volumes:
      - ./db:/var/lib/postgresql/data