services:
  db:
    container_name: f8-k13-Day-50
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    ports:
      - "5000:5432"
    volumes:
      - ./db:/var/lib/postgresql/data